### ISSUE TITLE
Synchronize Additional Checks with the Eclipse Validation Framework

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/validation#193]
As discussed on the 2nd level [VnV Kickoff](https://github.com/openETCS/validation/wiki/2nd-Level-VnV-Kickoff)

*** TODO Synchronize Additional Checks with Alexander Stante SysML using the plugin written by Alexander
    SCHEDULED: <2014-03-25 Di>
 - Involved: @astante @marcbehrens  
 - With ECLIPSE Validation Framework
 - Already basic checks implemented:
   - e.g. every flow-port has a type
   - checks can be extended
   - on what kind of uml elements the test is executed
   - write differentiation between error and warning
   - write description on what should be checked
   - Intention: To provide a check on the modeling guidelines
 - Checks is written in JAVA code
   - static tests
   - can be initiated in BATCH or continuously executed
   - can be written with OCL
   - Alexander Stante can add tests and can provide training for writing tests
 - [ ] Issue to initiate an implementation of checks
   - on what type of issue is this test to be applied on
   - what should the checks do
   - is the result a warning or an error
   - name the constraints (=name of test)
   - no limitation to traversing the model on tests
   - test should be executed on a named element
   - only UML-elements can be accesses on the validation framework
     - also ECORE models can be accessed
   - starting point of the checks is always just one element
 - [ ] a specific use case should be written for the checks
 - Checks needed on
   - [ ] SysML to scade system consistency checks
     - [ ] Ask Esterel on the constraints @BerndHekele 
     - [ ] e.g. unique naming of elements itself
   - [ ] Requirements consistency check
   - [ ] Consistency with the data dictionary is possile
 - Used for constraints on SysML itself
 - https://github.com/openETCS/toolchain/wiki/SysML-Constraint-Checker-Plugin
 - existing tests are to be found here and are based on ECLIPSE Validation Framework https://github.com/openETCS/toolchain/tree/master/tool/bundles/org.openetcs.sysml.constraints/src/org/openetcs/sysml/constraints
   - active tests are listed here: https://github.com/openETCS/toolchain/blob/master/tool/bundles/org.openetcs.sysml.constraints/plugin.xml
     - severity
     - executed on element
     - other information the tests

**Comment by MarcBehrens** [comment]
Coding rules are now part of [D4.2.2](https://github.com/openETCS/validation/blob/master/Reports/D4.2/D4.2.2-VV-Implementation/D4.2.2.pdf)

The use of the Eclipse Framework deferred with the decision to develop the model with SCADE.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Synchronize Additional Checks with the Eclipse Validation Framework (#193)" gesendet am 12.06.2015 16:58:16. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.

**Comment by RobertoKretschmer** [comment]
I will be out of the office starting 05.06.2015 and will not return until 20.06.2015

Ich werde mich sobald wie m�glich bei Ihnen melden.
Bei dringenden Angelegenheiten wenden Sie sich bitte an:
Carsten.Kuebler@twt-gmbh.de

I will get back to you as soon as possible.
In case of urgent matters please contact:
Carsten.Kuebler@twt-gmbh.de



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [validation] Synchronize Additional Checks with the Eclipse Validation Framework (#193)" gesendet am 12.06.2015 16:58:00. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend diese Person abwesend ist.
